- CHANGELOG.md
https://github.com/treely/boemly/releases
> Remove changelog since it's included in the releases

- src/components/BoemlyThemeProvider/BoemlyThemeProvider.test.tsx
- src/components/BoemlyThemeProvider/BoemlyThemeProvider.tsx
- src/types/BorderRadiiCustomization.ts
- src/utils/getTheme.ts
- stories/Customizations.stories.mdx
Addresses https://github.com/treely/boemly/issues/15
> feat(BoemlyThemeProvider): Add border radius customization

- package-lock.json
- package.json
> Installed markdown-to-jsx as a dependency

- src/components/DeleteConfirm/DeleteConfirm.stories.tsx
- src/components/DeleteConfirm/DeleteConfirm.test.tsx
- src/components/DeleteConfirm/DeleteConfirm.tsx
- src/components/DeleteConfirm/index.ts
- src/index.tsx
Staging docs link: https://boemly-git-lu-implement-delete-confirm-treely.vercel.app/?path=/story/components-deleteconfirm--default
> feat(DeleteConfirm): Implement component to confirm a deletion

- src/components/AvatarWithName/AvatarWithName.stories.tsx
- src/components/AvatarWithName/AvatarWithName.test.tsx
- src/components/AvatarWithName/AvatarWithName.tsx
- src/components/ContactArea/ContactArea.test.tsx
- src/components/QuoteCard/QuoteCard.test.tsx
New property `orientation` added to AvatarWithName component for vertical or horizontal alignment.
> Add 'orientation' property to AvatarWithName component

- src/components/SplitScreen/styles.ts
I'm removing this CSS code since it should not be in the component library. We need to implement this code in the app where we use the component library.
> feat(SplitScreen): Clean up unneeded CSS

- src/stories/tokens/Font Sizes.stories.tsx
> Add font size to token documentation

- package-lock.json
Fixes warning `Browserslist: caniuse-lite is outdated.`
> fix: Update browserslist

- __mocks__/styleMock.js
- package-lock.json
- package.json
- src/components/BoemlyFormControl/BoemlyFormControl.stories.tsx
- src/components/BoemlyFormControl/BoemlyFormControl.test.tsx
- src/components/BoemlyFormControl/BoemlyFormControl.tsx
- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.test.tsx
- src/components/DatePicker/DatePicker.tsx
- src/components/DatePicker/index.ts
Contributes to story: https://trello.com/c/9q47veqZ
> Add DatePicker component

- package-lock.json
- src/components/Slider/Slider.tsx
> fix(Dependencies): Update @chakra-ui/react

- src/constants/componentCustomizations.tsx
Fixes https://github.com/treely/boemly/issues/131
> fix(Select): Update font size of the  and  Select fields

- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.tsx
> feat(DatePicker): Allow styling with all InputGroup props

- src/components/BoemlyFormControl/BoemlyFormControl.stories.tsx
- src/components/BoemlyFormControl/BoemlyFormControl.test.tsx
- src/components/BoemlyFormControl/BoemlyFormControl.tsx
- src/components/Slider/Slider.test.tsx
- src/components/Slider/Slider.tsx
Contributes to https://trello.com/c/NFnpZeY5/244-interactive-calculator-for-forest-owners-5-8
> Make Slider component responsive

- src/components/DefaultSectionContainer/DefaultSectionContainer.test.tsx
- src/components/DefaultSectionContainer/DefaultSectionContainer.tsx
- src/utils/__tests__/convertToKebabCase.test.ts
- src/utils/convertToKebabCase.ts
Story: https://docs.google.com/document/d/1ii2kViX6YzdjV65fkvcIz_u5JHcVECaBL-szSn1c3fE/edit
> feat(DefaultSectionContainer): Add title property

- src/components/BoemlySteps/BoemlySteps.stories.tsx
- src/components/BoemlySteps/BoemlySteps.tsx
See https://github.com/treely/app/pull/820#discussion_r1341365281
> feat(BoemlySteps): Make onClick optional

- src/components/ConfirmAction/ConfirmAction.stories.tsx
- src/components/ConfirmAction/ConfirmAction.test.tsx
- src/components/ConfirmAction/ConfirmAction.tsx
- src/components/ConfirmAction/index.ts
- src/index.tsx
Story: https://trello.com/c/5von0bts/502-functionality-to-remove-certification-documents-from-platform-5-13
Preview: https://boemly-b0zu9r149-treely.vercel.app/?path=/story/components-confirmaction--minimal
> feat(confirm-action): implement component

- src/components/BoemlyTabs/BoemlyTabs.stories.tsx
- src/components/BoemlyTabs/BoemlyTabs.test.tsx
- src/components/BoemlyTabs/BoemlyTabs.tsx
- src/components/BoemlyTabs/LineTabButton.tsx
- src/components/BoemlyTabs/SolidTabButton.tsx
https://trello.com/c/eDgYEYYg/552-fs-display-in-the-platform-5-13
BoemlyTabs -> Solid
> feat: Add Solid Tab

- src/components/BoemlyFormControl/BoemlyFormControl.test.tsx
- src/components/Select/Select.stories.tsx
- src/components/Select/Select.test.tsx
- src/components/Select/Select.tsx
- src/constants/componentCustomizations.tsx
- FIx select menu, replace Vstack with Menu and use portal to display menu options
> fix(select): open menu in portal, replace vstack with menu

- src/components/Select/Select.tsx
- Fix select border radius, box shadow on hover
> fix(select): select menu shadow and borderRadius fix

- src/components/LabelTextPair/LabelTextPair.stories.tsx
- src/components/LabelTextPair/LabelTextPair.test.tsx
- src/components/LabelTextPair/LabelTextPair.tsx
needed for the story design: https://www.figma.com/design/WU0BNOCYT7yS6vmtMqK1Rz/Platform-V2?node-id=1046-2721&m=dev
> feat: update label-text-pair to have is-disabled prop

- package-lock.json
- package.json
https://www.chakra-ui.com/blog/01-chakra-v2-vs-v3-a-detailed-comparison
> build: remove unnecessary dependencies

- package-lock.json
- package.json
- src/components/Select/Select.test.tsx
- src/components/Select/Select.tsx
Update "@chakra-ui/react": "^3.13.0", done because of the InputGroup, which I needed.
> feat: migrate select component

- src/constants/componentCustomizations.tsx
Note:
The top border is missing because chakra got rid of it
v2 documentation:
https://v2.chakra-ui.com/docs/components/accordion/usage
v3 documentation:
https://chakra-ui.com/docs/components/accordion
> fix: accordion styling
