treely/boemly

src/components/Expandable/Expandable.tsx

Previously, any icon would be aligned to the left top. Only square phosphor-icons with size 80 would appear centered.
This change centers all icons - or really any jsx element provided in the icon prop - vertically and horizontally in the parent div.
Before:
After:

fix(Expandable): Center icon

---

src/components/NavItem/NavItem.stories.tsx

A navigation item should be a <a href=""></a> element. Not a button. Since in e.g. Next.js there are custom links that should be used it makes not much sense to have the NavItem in a component library.

Deprecate NavItem component

---

src/constants/componentCustomizations.tsx
src/stories/components/Select.stories.tsx

The `Select` component of ChakraUI has already been usable in Boemly but was not documented and customized.

feat(Select): Document and customize the Select component

---

src/components/Container/Container.tsx
src/components/QuoteCard/QuoteCard.tsx

fixes treely/app#585
Also makes it that if a header is present on the container, the children will only take up the rest of the space instead of being the same size as the parent.
And it fixes the alignment here: https://boemly.tree.ly/?path=/story/components-contactarea--default-props

fix(QuoteCard): Align avatar to bottom of container

---

src/components/BoemlyTabs/BoemlyTabs.tsx

Previously, the scrollbar would show on windows even though there was no overflow:

fix(BoemlyTabs): Hide scrollbar when not needed.

---

package-lock.json
package.json

It seems that the small-lib preset for size-limit does not support css files.
This PR switches to the big-lib preset and adds the webpack-css compatibility plugin.
Since size-limit recommends the  big-lib preset  for libraries larger than 10kb, so this should be more fitting either way.
This is the result it would give for #118

Upgrade size-limit

---

src/constants/buttonVariants.ts
src/stories/components/Button.stories.tsx
src/types/ButtonVariant.ts

fixes https://github.com/treely/boemly/issues/134

Document `ghost` variant of `Button`

---

src/components/RichText/RichText.tsx

Adds styling definition for `span` elements in the `RichText` component.

fix(RichText): Add span styling definition

---

src/components/RichText/RichText.stories.tsx
src/components/RichText/RichText.test.tsx
src/components/RichText/RichText.tsx

Uses the same logic as probablyup/markdown-to-jsx to decide whether to render the content as inline or block.
Wraps inline content in a chakra-ui `<Text>` tag and applies the `textProps` to it. Behaviour for block content remains unchanged.

feat(RichText): Render inline content in line

---

src/components/DatePicker/DatePicker.test.tsx
src/components/DatePicker/DatePicker.tsx

Opens the datepicker and focusses on the input element when the user clicks on the calender icon.

fix(DatePicker): Open on click on InputAddon

---

tsconfig.json

This change removes the `....stories.d.ts` files from the `dist` folder.

Ignore stories in build

---

src/components/BoemlyList/BoemlyList.tsx

Align icon with the first line of the text
fixes treely/app#837

fix(BoemlyList): Icon alignment

---

src/components/DatePicker/styles.ts

Fix(DatePicker): Remove unintended label

---

src/components/DefaultSectionHeader/DefaultSectionHeader.tsx

Fixes https://github.com/treely/app/issues/959

fix(DefaultSectionHeader): Font color for rich text sub title

---

src/components/Header/Header.stories.tsx
src/components/Header/Header.test.tsx
src/components/Header/Header.tsx

https://trello.com/c/ykivdeGd/467-silvaconsult-logo-in-mobile-header-is-cut-off-and-too-small
https://trello.com/c/KawGcf7b/336-improvements-carbon-buyer-confirmation
https://boemly-4dyw19o0q-treely.vercel.app/?path=/story/components-header--default-props
https://boemly-dx08fueam-treely.vercel.app/?path=/story/components-header--default-props

fix(Header): Fix the Header for mobile screen

---

src/components/DatePicker/DatePicker.tsx

I made a mistake in setting this to `Date | undefined` in #204 
`onSelect` gets fired when a date in the component is selected. So it is always defined.

fix(datepicker): date in onSelect prop is always defined

---

src/components/Slider/Slider.stories.tsx
src/components/Slider/Slider.test.tsx
src/components/Slider/Slider.tsx

I just came across the problem that when I use the new Slider and want to change the value from "outside" (in this case the input field) I don't have the possibility to change the slider value because we don't have a prop to set the value. This solves this problem.

feat(slider): enable change of slider value though a prop

---

src/components/Select/Select.tsx

- Fix select position, background, and display so it display with white background, and always position below the select

fix(select): select list background, position, display

---

src/components/TextCardWithIcon/TextCardWithIcon.tsx

In `TextCarousel` component in strapi-slices the button of `TextCardWithIcon` component moves depending of amount of the text; additionally in combination with other cards the button gains some space around, what is not preferable behaviour. This PR fixis it, unfortunately the fix is not possible to see it in storybook

fix: fix the text-card button

---

src/constants/customizations.ts

Set fallback fonts to sans serif fonts so that its doesn't render the page with times new roman if the main fonts cannot be loaded.

fix: set fallback fonts

---

src/components/BoemlyFormControl/BoemlyFormControl.stories.tsx
src/components/Select/Select.stories.tsx
src/components/Select/Select.test.tsx
src/components/Select/Select.tsx

- add a preventDeselection flag for single select so a user isn't allowed to deselect a previously selected option, they can only change it to another option. This is needed in the locale(Language) selection where one language needs to be selected.

feat(select): add an option to not allow deselecting a selected option

---

src/components/Select/Select.tsx

Fixes: https://trello.com/c/gUy7r9z7/636-set-boemly-select-text-color-to-always-be-black

fix: select text color

---

src/components/Select/Select.tsx

Impediment: https://trello.com/c/jsan91I0/648-project-design-studio-feasibility-study-editor-bug-reported-from-tnl-partner-project-developer
This PR was tested with npm run build and npm pack in boemly and then the .tgz file created in boemly was installed to app repository. Added in app in NormalStockForm component the prop `dropdownWidth:"3xs"` on line 533. Then on Firefox browser opened http://localhost:3000/app/projects/ in any project where there is no FS study yet; opened 'Create FS Study' and filled the fields on the first step. On the second step the issue is in "Yield Table" Select dropdown.
Also the issue appears in fpm in the page https://fpm.tree.ly/app/transactions on "From Account" and "To Account" dropdowns.

feat: add dropdwonWidth prop to select
